# Point to the central manager
CONDOR_HOST = svpvclus01.cnao.group

# Force HTCondor to use your OS /etc/hosts file so it can resolve names
ENABLE_ASYNC_DNS = False

# No local daemons
DAEMON_LIST = NONE
